before_script:
  - node --version
  - npm --version

stages:
  - test

job_test_all:
  stage: test
  script:
    - npm install
    - npm run check-build
    - npm test
  cache:
    key: "test"
    paths:
      - node_modules/
  only:
    - master
